jobs:
  analyse_js:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          command: yarn jest
          name: Jest
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - persist_to_workspace:
          paths: .
          root: .
orbs:
  rn: react-native-community/react-native@4.4.2
version: 2.1
workflows:
  test:
    jobs:
      - checkout_code
      - analyse_js:
          requires:
            - checkout_code
      - rn/android_build:
          build_type: debug
          name: build_android_debug
          on_after_initialize: chmod +x ./android/gradlew
          requires:
            - analyse_js
      - rn/android_build:
          build_type: release
          name: build_android_release
          on_after_initialize: chmod +x ./android/gradlew
          requires:
            - analyse_js
      - rn/android_test:
          requires:
            - build_android_release